-- Hostel Operations — PostgreSQL schema for Supabase
-- Generated from the local Cloudflare D1 (SQLite) database.
-- Run this FIRST in the Supabase SQL Editor, then run 02_data.sql.

CREATE TABLE IF NOT EXISTS "hostel_properties" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "address" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "electricity_rate" double precision DEFAULT 0 NOT NULL,
  "monthly_cleaning_fee" double precision DEFAULT 0 NOT NULL,
  "monthly_water_dispenser_fee" double precision DEFAULT 0 NOT NULL,
  CONSTRAINT hostel_properties_code_unique UNIQUE ("code")
);

CREATE TABLE IF NOT EXISTS "hostel_units" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hostel_id" bigint NOT NULL,
  "unit_code" text NOT NULL,
  "address" text DEFAULT '' NOT NULL,
  "gender" text DEFAULT 'mixed' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "owner_name" text DEFAULT '' NOT NULL,
  "lease_end_date" text,
  "surrender_date" text,
  "surrender_notes" text DEFAULT '' NOT NULL,
  CONSTRAINT hostel_unit_unique UNIQUE ("hostel_id", "unit_code"),
  FOREIGN KEY ("hostel_id") REFERENCES "hostel_properties"("id")
);

CREATE TABLE IF NOT EXISTS "access_cards" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unit_id" bigint NOT NULL,
  "card_code" text NOT NULL,
  "deposit_amount" double precision DEFAULT 0 NOT NULL,
  "status" text DEFAULT 'available' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  CONSTRAINT access_cards_card_code_unique UNIQUE ("card_code"),
  FOREIGN KEY ("unit_id") REFERENCES "hostel_units"("id")
);

CREATE TABLE IF NOT EXISTS "hostel_rooms" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unit_id" bigint NOT NULL,
  "room_label" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "bathroom_type" text DEFAULT 'unknown' NOT NULL,
  "sales_rate" double precision,
  "room_type" text DEFAULT 'auto' NOT NULL,
  "promotion_rate" double precision,
  "promotion_start_date" text,
  "promotion_end_date" text,
  "meter_serial" text DEFAULT '' NOT NULL,
  CONSTRAINT hostel_room_unique UNIQUE ("unit_id", "room_label"),
  FOREIGN KEY ("unit_id") REFERENCES "hostel_units"("id")
);

CREATE TABLE IF NOT EXISTS "bed_spaces" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "room_id" bigint NOT NULL,
  "bed_label" text NOT NULL,
  "legacy_code" text NOT NULL,
  "status" text DEFAULT 'vacant' NOT NULL,
  "special_use" text,
  "monthly_rental" double precision,
  "legacy_access_card_deposit" double precision,
  "updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "bed_type" text DEFAULT 'unknown' NOT NULL,
  "meter_serial" text DEFAULT '' NOT NULL,
  CONSTRAINT room_bed_unique UNIQUE ("room_id", "bed_label"),
  FOREIGN KEY ("room_id") REFERENCES "hostel_rooms"("id")
);

CREATE TABLE IF NOT EXISTS "student_profiles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_key" text NOT NULL,
  "student_code" text DEFAULT '' NOT NULL,
  "full_name" text NOT NULL,
  "nationality" text DEFAULT '' NOT NULL,
  "hometown" text DEFAULT '' NOT NULL,
  "course" text DEFAULT '' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "identity_no" text DEFAULT '' NOT NULL,
  "contact_number" text DEFAULT '' NOT NULL,
  "email" text DEFAULT '' NOT NULL,
  "date_of_birth" text,
  "gender" text DEFAULT 'unspecified' NOT NULL,
  "race" text DEFAULT '' NOT NULL,
  "religion" text DEFAULT '' NOT NULL,
  "school" text DEFAULT '' NOT NULL,
  "application_form_no" text DEFAULT '' NOT NULL,
  "receipt_no" text DEFAULT '' NOT NULL,
  "salesperson" text DEFAULT '' NOT NULL,
  "agency" text DEFAULT '' NOT NULL,
  "remarks" text DEFAULT '' NOT NULL,
  CONSTRAINT student_profiles_source_key_unique UNIQUE ("source_key")
);

CREATE TABLE IF NOT EXISTS "accommodation_assignments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_key" text NOT NULL,
  "student_id" bigint NOT NULL,
  "bed_space_id" bigint NOT NULL,
  "monthly_rental" double precision,
  "security_deposit" double precision,
  "access_card_deposit" double precision,
  "salesperson" text DEFAULT '' NOT NULL,
  "check_in_date" text,
  "agreement_start_date" text,
  "agreement_end_date" text,
  "agreement_duration" text DEFAULT '' NOT NULL,
  "check_out_date" text,
  "check_in_meter" double precision,
  "remarks" text DEFAULT '' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "parking_deposit" double precision,
  "check_out_meter" double precision,
  "source_reservation_id" bigint,
  CONSTRAINT accommodation_assignments_source_key_unique UNIQUE ("source_key"),
  FOREIGN KEY ("bed_space_id") REFERENCES "bed_spaces"("id"),
  FOREIGN KEY ("student_id") REFERENCES "student_profiles"("id")
);

CREATE TABLE IF NOT EXISTS "announcements" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "body" text NOT NULL,
  "audience_type" text DEFAULT 'all' NOT NULL,
  "hostel_id" bigint,
  "block_code" text DEFAULT '' NOT NULL,
  "unit_id" bigint,
  "priority" text DEFAULT 'normal' NOT NULL,
  "pinned" boolean DEFAULT false NOT NULL,
  "publish_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "expires_at" text,
  "created_by" text DEFAULT 'Administrator' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "status" text DEFAULT 'published' NOT NULL,
  FOREIGN KEY ("unit_id") REFERENCES "hostel_units"("id"),
  FOREIGN KEY ("hostel_id") REFERENCES "hostel_properties"("id")
);

CREATE TABLE IF NOT EXISTS "app_roles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_key" text NOT NULL,
  "name" text NOT NULL,
  "description" text DEFAULT '' NOT NULL,
  "is_system" boolean DEFAULT false NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  CONSTRAINT app_roles_role_key_unique UNIQUE ("role_key")
);

CREATE TABLE IF NOT EXISTS "app_users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text NOT NULL,
  "display_name" text NOT NULL,
  "role_id" bigint NOT NULL,
  "student_id" bigint,
  "status" text DEFAULT 'active' NOT NULL,
  "last_login_at" text,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "password_hash" text DEFAULT '' NOT NULL,
  CONSTRAINT app_users_email_unique UNIQUE ("email"),
  FOREIGN KEY ("student_id") REFERENCES "student_profiles"("id"),
  FOREIGN KEY ("role_id") REFERENCES "app_roles"("id")
);

CREATE TABLE IF NOT EXISTS "billing_cycles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "period_label" text NOT NULL,
  "cutoff_date" text NOT NULL,
  "due_date" text NOT NULL,
  "status" text DEFAULT 'draft' NOT NULL,
  "posted_at" text,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  CONSTRAINT billing_cycles_period_label_unique UNIQUE ("period_label")
);

CREATE TABLE IF NOT EXISTS "billing_invoices" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_no" text NOT NULL,
  "cycle_id" bigint NOT NULL,
  "student_id" bigint NOT NULL,
  "assignment_id" bigint,
  "due_date" text NOT NULL,
  "status" text DEFAULT 'unpaid' NOT NULL,
  "total_amount" double precision DEFAULT 0 NOT NULL,
  "amount_paid" double precision DEFAULT 0 NOT NULL,
  "invoice_frequency" text DEFAULT 'on-request' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  CONSTRAINT billing_invoices_invoice_no_unique UNIQUE ("invoice_no"),
  FOREIGN KEY ("assignment_id") REFERENCES "accommodation_assignments"("id"),
  FOREIGN KEY ("student_id") REFERENCES "student_profiles"("id"),
  FOREIGN KEY ("cycle_id") REFERENCES "billing_cycles"("id")
);

CREATE TABLE IF NOT EXISTS "billing_items" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_id" bigint NOT NULL,
  "item_type" text NOT NULL,
  "description" text NOT NULL,
  "quantity" double precision DEFAULT 1 NOT NULL,
  "rate" double precision DEFAULT 0 NOT NULL,
  "amount" double precision DEFAULT 0 NOT NULL,
  FOREIGN KEY ("invoice_id") REFERENCES "billing_invoices"("id")
);

CREATE TABLE IF NOT EXISTS "billing_item_adjustments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "billing_item_id" bigint NOT NULL,
  "previous_amount" double precision DEFAULT 0 NOT NULL,
  "new_amount" double precision DEFAULT 0 NOT NULL,
  "reason" text NOT NULL,
  "requested_by" text NOT NULL,
  "approval_status" text DEFAULT 'pending' NOT NULL,
  "approved_by" text DEFAULT '' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "approved_at" text,
  FOREIGN KEY ("billing_item_id") REFERENCES "billing_items"("id")
);

CREATE TABLE IF NOT EXISTS "stored_attachments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "context_type" text NOT NULL,
  "record_id" bigint NOT NULL,
  "object_key" text NOT NULL,
  "file_name" text NOT NULL,
  "content_type" text DEFAULT 'application/octet-stream' NOT NULL,
  "size_bytes" bigint DEFAULT 0 NOT NULL,
  "uploaded_by" text DEFAULT '' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  CONSTRAINT stored_attachments_object_key_unique UNIQUE ("object_key")
);

CREATE TABLE IF NOT EXISTS "billing_payment_records" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_id" bigint NOT NULL,
  "amount" double precision DEFAULT 0 NOT NULL,
  "reference" text DEFAULT '' NOT NULL,
  "status" text DEFAULT 'pending-verification' NOT NULL,
  "proof_attachment_id" bigint,
  "submitted_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "verified_at" text,
  "verified_by" text DEFAULT '' NOT NULL,
  "remark" text DEFAULT '' NOT NULL,
  "verified_amount" double precision,
  "actual_reference" text DEFAULT '' NOT NULL,
  "receipt_no" text DEFAULT '' NOT NULL,
  FOREIGN KEY ("proof_attachment_id") REFERENCES "stored_attachments"("id"),
  FOREIGN KEY ("invoice_id") REFERENCES "billing_invoices"("id")
);

CREATE TABLE IF NOT EXISTS "maintenance_tickets" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_no" text NOT NULL,
  "student_id" bigint,
  "hostel_id" bigint,
  "unit_id" bigint,
  "room_id" bigint,
  "category" text NOT NULL,
  "subcategory" text DEFAULT '' NOT NULL,
  "subject" text NOT NULL,
  "description" text DEFAULT '' NOT NULL,
  "priority" text DEFAULT 'average' NOT NULL,
  "status" text DEFAULT 'submitted' NOT NULL,
  "submitted_by_type" text DEFAULT 'staff' NOT NULL,
  "assigned_to" text DEFAULT '' NOT NULL,
  "attended_at" text,
  "completed_at" text,
  "cost_responsibility" text DEFAULT 'management' NOT NULL,
  "estimated_cost" double precision,
  "actual_cost" double precision,
  "student_charge" double precision,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  CONSTRAINT maintenance_tickets_ticket_no_unique UNIQUE ("ticket_no"),
  FOREIGN KEY ("room_id") REFERENCES "hostel_rooms"("id"),
  FOREIGN KEY ("unit_id") REFERENCES "hostel_units"("id"),
  FOREIGN KEY ("hostel_id") REFERENCES "hostel_properties"("id"),
  FOREIGN KEY ("student_id") REFERENCES "student_profiles"("id")
);

CREATE TABLE IF NOT EXISTS "general_costs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cost_date" text NOT NULL,
  "hostel_id" bigint,
  "unit_id" bigint,
  "ticket_id" bigint,
  "cost_type" text DEFAULT 'maintenance' NOT NULL,
  "description" text NOT NULL,
  "responsibility" text DEFAULT 'management' NOT NULL,
  "amount" double precision DEFAULT 0 NOT NULL,
  "student_charge" double precision DEFAULT 0 NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "created_by" text DEFAULT 'Administrator' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  FOREIGN KEY ("ticket_id") REFERENCES "maintenance_tickets"("id"),
  FOREIGN KEY ("unit_id") REFERENCES "hostel_units"("id"),
  FOREIGN KEY ("hostel_id") REFERENCES "hostel_properties"("id")
);

CREATE TABLE IF NOT EXISTS "meter_readings" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bed_space_id" bigint NOT NULL,
  "reading_date" text NOT NULL,
  "reading_value" double precision NOT NULL,
  "reading_type" text DEFAULT 'monthly' NOT NULL,
  "submitted_by" text DEFAULT 'Maintenance Team' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "room_id" bigint,
  FOREIGN KEY ("bed_space_id") REFERENCES "bed_spaces"("id"),
  FOREIGN KEY ("room_id") REFERENCES "hostel_rooms"("id")
);

CREATE TABLE IF NOT EXISTS "parking_lots" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hostel_id" bigint NOT NULL,
  "unit_id" bigint,
  "lot_number" text NOT NULL,
  "status" text DEFAULT 'available' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  CONSTRAINT parking_lot_unique UNIQUE ("hostel_id", "lot_number"),
  FOREIGN KEY ("unit_id") REFERENCES "hostel_units"("id"),
  FOREIGN KEY ("hostel_id") REFERENCES "hostel_properties"("id")
);

CREATE TABLE IF NOT EXISTS "owner_parking_payments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unit_id" bigint NOT NULL,
  "parking_lot_id" bigint,
  "period" text DEFAULT '' NOT NULL,
  "amount" double precision DEFAULT 0 NOT NULL,
  "payment_date" text NOT NULL,
  "method" text DEFAULT 'bank-transfer' NOT NULL,
  "reference" text DEFAULT '' NOT NULL,
  "status" text DEFAULT 'paid' NOT NULL,
  "remarks" text DEFAULT '' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  FOREIGN KEY ("parking_lot_id") REFERENCES "parking_lots"("id"),
  FOREIGN KEY ("unit_id") REFERENCES "hostel_units"("id")
);

CREATE TABLE IF NOT EXISTS "parking_rentals" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parking_lot_id" bigint NOT NULL,
  "student_id" bigint,
  "tenant_type" text DEFAULT 'in-house' NOT NULL,
  "tenant_name" text NOT NULL,
  "contact_number" text DEFAULT '' NOT NULL,
  "unit_number" text DEFAULT '' NOT NULL,
  "car_plate_number" text DEFAULT '' NOT NULL,
  "car_model" text DEFAULT '' NOT NULL,
  "monthly_rental" double precision DEFAULT 0 NOT NULL,
  "deposit_amount" double precision DEFAULT 0 NOT NULL,
  "start_date" text NOT NULL,
  "end_date" text,
  "paid_until" text,
  "billing_frequency" text DEFAULT 'monthly' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "package_months" bigint DEFAULT 1 NOT NULL,
  "next_due_date" text,
  "payment_status" text DEFAULT 'not-due' NOT NULL,
  FOREIGN KEY ("student_id") REFERENCES "student_profiles"("id"),
  FOREIGN KEY ("parking_lot_id") REFERENCES "parking_lots"("id")
);

CREATE TABLE IF NOT EXISTS "reminder_templates" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reminder_key" text NOT NULL,
  "day_of_month" bigint NOT NULL,
  "subject" text NOT NULL,
  "message" text NOT NULL,
  "enabled" boolean DEFAULT true NOT NULL,
  "updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  CONSTRAINT reminder_templates_reminder_key_unique UNIQUE ("reminder_key")
);

CREATE TABLE IF NOT EXISTS "reservations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference_no" text NOT NULL,
  "student_name" text NOT NULL,
  "preferred_hostel_id" bigint,
  "preferred_gender" text DEFAULT 'unspecified' NOT NULL,
  "room_type" text DEFAULT 'any' NOT NULL,
  "bathroom_type" text DEFAULT 'any' NOT NULL,
  "target_move_in_date" text NOT NULL,
  "budget_max" double precision,
  "provisional_bed_space_id" bigint,
  "hold_expires_at" text,
  "status" text DEFAULT 'reserved' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "room_category" text DEFAULT 'any' NOT NULL,
  "expected_end_date" text,
  "payment_status" text DEFAULT 'unpaid' NOT NULL,
  "amount_paid" double precision DEFAULT 0 NOT NULL,
  "total_payable" double precision,
  "payment_reference" text DEFAULT '' NOT NULL,
  "inventory_committed" boolean DEFAULT false NOT NULL,
  "payment_updated_at" text,
  "reservation_type" text DEFAULT 'individual' NOT NULL,
  "representative_type" text DEFAULT 'person' NOT NULL,
  "sales_person" text DEFAULT '' NOT NULL,
  "group_size" bigint DEFAULT 1 NOT NULL,
  "preferred_unit_id" bigint,
  "assigned_bed_space_id" bigint,
  "converted_at" text,
  CONSTRAINT reservations_reference_no_unique UNIQUE ("reference_no"),
  FOREIGN KEY ("provisional_bed_space_id") REFERENCES "bed_spaces"("id"),
  FOREIGN KEY ("preferred_hostel_id") REFERENCES "hostel_properties"("id"),
  FOREIGN KEY ("assigned_bed_space_id") REFERENCES "bed_spaces"("id"),
  FOREIGN KEY ("preferred_unit_id") REFERENCES "hostel_units"("id")
);

CREATE TABLE IF NOT EXISTS "reservation_charges" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" bigint NOT NULL,
  "charge_type" text NOT NULL,
  "amount" double precision DEFAULT 0 NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id")
);

CREATE TABLE IF NOT EXISTS "reservation_payments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" bigint NOT NULL,
  "amount" double precision DEFAULT 0 NOT NULL,
  "reference" text DEFAULT '' NOT NULL,
  "payment_method" text DEFAULT 'bank-transfer' NOT NULL,
  "paid_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id")
);

CREATE TABLE IF NOT EXISTS "role_permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" bigint NOT NULL,
  "module_key" text NOT NULL,
  "can_view" boolean DEFAULT false NOT NULL,
  "can_create" boolean DEFAULT false NOT NULL,
  "can_edit" boolean DEFAULT false NOT NULL,
  "can_delete" boolean DEFAULT false NOT NULL,
  "can_approve" boolean DEFAULT false NOT NULL,
  CONSTRAINT role_permission_unique UNIQUE ("role_id", "module_key"),
  FOREIGN KEY ("role_id") REFERENCES "app_roles"("id")
);

CREATE TABLE IF NOT EXISTS "schools" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  CONSTRAINT schools_name_unique UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS "student_rate_changes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assignment_id" bigint NOT NULL,
  "effective_date" text NOT NULL,
  "monthly_rental" double precision,
  "security_deposit" double precision,
  "reason" text DEFAULT '' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  FOREIGN KEY ("assignment_id") REFERENCES "accommodation_assignments"("id")
);

CREATE TABLE IF NOT EXISTS "ticket_categories" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" text NOT NULL,
  "subcategory" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "sort_order" bigint DEFAULT 0 NOT NULL,
  CONSTRAINT ticket_category_unique UNIQUE ("category", "subcategory")
);

CREATE TABLE IF NOT EXISTS "ticket_messages" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" bigint NOT NULL,
  "author_name" text NOT NULL,
  "author_role" text DEFAULT 'staff' NOT NULL,
  "message" text NOT NULL,
  "status_after" text,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  FOREIGN KEY ("ticket_id") REFERENCES "maintenance_tickets"("id")
);

CREATE TABLE IF NOT EXISTS "unit_owner_details" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unit_id" bigint NOT NULL,
  "owner_name" text DEFAULT '' NOT NULL,
  "primary_contact_name" text DEFAULT '' NOT NULL,
  "primary_contact_phone" text DEFAULT '' NOT NULL,
  "secondary_contact_name" text DEFAULT '' NOT NULL,
  "secondary_contact_phone" text DEFAULT '' NOT NULL,
  "lease_start_date" text,
  "lease_end_date" text,
  "monthly_lease_rental" double precision,
  "security_deposit" double precision,
  "notes" text DEFAULT '' NOT NULL,
  "updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "agreement_type" text DEFAULT 'rental' NOT NULL,
  "bank_account_number" text DEFAULT '' NOT NULL,
  "bank_account_holder" text DEFAULT '' NOT NULL,
  "bank_name" text DEFAULT '' NOT NULL,
  "service_percentage" double precision,
  "utility_deposit" double precision,
  "commission_amount" double precision,
  "tnb_account" text DEFAULT '' NOT NULL,
  "air_selangor_account" text DEFAULT '' NOT NULL,
  "indah_water_account" text DEFAULT '' NOT NULL,
  "monthly_cleaning_fee" double precision,
  "monthly_water_dispenser_fee" double precision,
  "owner_identity_no" text DEFAULT '' NOT NULL,
  "owner_email" text DEFAULT '' NOT NULL,
  "registered_address" text DEFAULT '' NOT NULL,
  CONSTRAINT unit_owner_unique UNIQUE ("unit_id"),
  FOREIGN KEY ("unit_id") REFERENCES "hostel_units"("id")
);

CREATE TABLE IF NOT EXISTS "unit_services" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unit_id" bigint NOT NULL,
  "service_type" text NOT NULL,
  "provider" text DEFAULT '' NOT NULL,
  "account_reference" text DEFAULT '' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "surrender_action" text DEFAULT 'review' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  "account_holder_name" text DEFAULT '' NOT NULL,
  "line_type" text DEFAULT 'not-applicable' NOT NULL,
  "contract_end_date" text,
  "service_package" text DEFAULT '' NOT NULL,
  "username" text DEFAULT '' NOT NULL,
  "password" text DEFAULT '' NOT NULL,
  "remarks" text DEFAULT '' NOT NULL,
  FOREIGN KEY ("unit_id") REFERENCES "hostel_units"("id")
);

CREATE TABLE IF NOT EXISTS "user_sessions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token_hash" text NOT NULL,
  "user_id" bigint NOT NULL,
  "expires_at" text NOT NULL,
  "created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
  CONSTRAINT user_sessions_token_hash_unique UNIQUE ("token_hash"),
  FOREIGN KEY ("user_id") REFERENCES "app_users"("id")
);
