CREATE TABLE "access_cards" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "access_cards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"unit_id" bigint NOT NULL,
	"card_code" text NOT NULL,
	"deposit_amount" double precision DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'available' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "access_cards_card_code_unique" UNIQUE("card_code")
);
--> statement-breakpoint
CREATE TABLE "accommodation_assignments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accommodation_assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"source_key" text NOT NULL,
	"student_id" bigint NOT NULL,
	"bed_space_id" bigint NOT NULL,
	"monthly_rental" double precision,
	"security_deposit" double precision,
	"access_card_deposit" double precision,
	"parking_deposit" double precision,
	"salesperson" text DEFAULT '' NOT NULL,
	"check_in_date" text,
	"agreement_start_date" text,
	"agreement_end_date" text,
	"agreement_duration" text DEFAULT '' NOT NULL,
	"check_out_date" text,
	"check_in_meter" double precision,
	"check_out_meter" double precision,
	"source_reservation_id" bigint,
	"remarks" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "accommodation_assignments_source_key_unique" UNIQUE("source_key")
);
--> statement-breakpoint
CREATE TABLE "announcements" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "announcements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"body" text NOT NULL,
	"audience_type" text DEFAULT 'all' NOT NULL,
	"hostel_id" bigint,
	"block_code" text DEFAULT '' NOT NULL,
	"unit_id" bigint,
	"priority" text DEFAULT 'normal' NOT NULL,
	"status" text DEFAULT 'published' NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"publish_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	"expires_at" text,
	"created_by" text DEFAULT 'Administrator' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role_key" text NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "app_roles_role_key_unique" UNIQUE("role_key")
);
--> statement-breakpoint
CREATE TABLE "app_users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"display_name" text NOT NULL,
	"role_id" bigint NOT NULL,
	"student_id" bigint,
	"status" text DEFAULT 'active' NOT NULL,
	"password_hash" text DEFAULT '' NOT NULL,
	"last_login_at" text,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "app_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "bed_spaces" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bed_spaces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"room_id" bigint NOT NULL,
	"bed_label" text NOT NULL,
	"legacy_code" text NOT NULL,
	"status" text DEFAULT 'vacant' NOT NULL,
	"special_use" text,
	"bed_type" text DEFAULT 'unknown' NOT NULL,
	"meter_serial" text DEFAULT '' NOT NULL,
	"monthly_rental" double precision,
	"legacy_access_card_deposit" double precision,
	"updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "bed_spaces_legacy_code_unique" UNIQUE("legacy_code")
);
--> statement-breakpoint
CREATE TABLE "billing_cycles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing_cycles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"period_label" text NOT NULL,
	"cutoff_date" text NOT NULL,
	"due_date" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"posted_at" text,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "billing_cycles_period_label_unique" UNIQUE("period_label")
);
--> statement-breakpoint
CREATE TABLE "billing_invoices" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing_invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"invoice_no" text NOT NULL,
	"cycle_id" bigint NOT NULL,
	"student_id" bigint NOT NULL,
	"assignment_id" bigint,
	"due_date" text NOT NULL,
	"status" text DEFAULT 'unpaid' NOT NULL,
	"total_amount" double precision DEFAULT 0 NOT NULL,
	"amount_paid" double precision DEFAULT 0 NOT NULL,
	"invoice_frequency" text DEFAULT 'on-request' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "billing_invoices_invoice_no_unique" UNIQUE("invoice_no")
);
--> statement-breakpoint
CREATE TABLE "billing_item_adjustments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing_item_adjustments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"billing_item_id" bigint NOT NULL,
	"previous_amount" double precision DEFAULT 0 NOT NULL,
	"new_amount" double precision DEFAULT 0 NOT NULL,
	"reason" text NOT NULL,
	"requested_by" text NOT NULL,
	"approval_status" text DEFAULT 'pending' NOT NULL,
	"approved_by" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	"approved_at" text
);
--> statement-breakpoint
CREATE TABLE "billing_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"invoice_id" bigint NOT NULL,
	"item_type" text NOT NULL,
	"description" text NOT NULL,
	"quantity" double precision DEFAULT 1 NOT NULL,
	"rate" double precision DEFAULT 0 NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "billing_payment_records" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing_payment_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"invoice_id" bigint NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"reference" text DEFAULT '' NOT NULL,
	"remark" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'pending-verification' NOT NULL,
	"proof_attachment_id" bigint,
	"submitted_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	"verified_at" text,
	"verified_by" text DEFAULT '' NOT NULL,
	"verified_amount" double precision,
	"actual_reference" text DEFAULT '' NOT NULL,
	"receipt_no" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "general_costs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "general_costs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"cost_date" text NOT NULL,
	"hostel_id" bigint,
	"unit_id" bigint,
	"ticket_id" bigint,
	"cost_type" text DEFAULT 'maintenance' NOT NULL,
	"description" text NOT NULL,
	"responsibility" text DEFAULT 'management' NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"student_charge" double precision DEFAULT 0 NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_by" text DEFAULT 'Administrator' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hostel_properties" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hostel_properties_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name" text NOT NULL,
	"address" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"electricity_rate" double precision DEFAULT 0 NOT NULL,
	"monthly_cleaning_fee" double precision DEFAULT 0 NOT NULL,
	"monthly_water_dispenser_fee" double precision DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "hostel_properties_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "hostel_rooms" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hostel_rooms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"unit_id" bigint NOT NULL,
	"room_label" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"bathroom_type" text DEFAULT 'unknown' NOT NULL,
	"room_type" text DEFAULT 'auto' NOT NULL,
	"sales_rate" double precision,
	"promotion_rate" double precision,
	"promotion_start_date" text,
	"promotion_end_date" text,
	"meter_serial" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hostel_units" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hostel_units_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hostel_id" bigint NOT NULL,
	"unit_code" text NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"gender" text DEFAULT 'mixed' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"owner_name" text DEFAULT '' NOT NULL,
	"lease_end_date" text,
	"surrender_date" text,
	"surrender_notes" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "complaints" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "complaints_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ticket_no" text NOT NULL,
	"student_id" bigint NOT NULL,
	"category" text NOT NULL,
	"subject" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"priority" text DEFAULT 'medium' NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"assigned_to" text DEFAULT 'Facilities Team' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	"updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "complaints_ticket_no_unique" UNIQUE("ticket_no")
);
--> statement-breakpoint
CREATE TABLE "hostels" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hostels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"warden_name" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoices" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"invoice_no" text NOT NULL,
	"student_id" bigint NOT NULL,
	"description" text NOT NULL,
	"amount" double precision NOT NULL,
	"due_date" text NOT NULL,
	"status" text DEFAULT 'unpaid' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "invoices_invoice_no_unique" UNIQUE("invoice_no")
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"invoice_id" bigint NOT NULL,
	"amount" double precision NOT NULL,
	"method" text DEFAULT 'bank transfer' NOT NULL,
	"reference" text DEFAULT '' NOT NULL,
	"paid_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rooms" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rooms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hostel_id" bigint NOT NULL,
	"room_number" text NOT NULL,
	"floor" bigint DEFAULT 1 NOT NULL,
	"capacity" bigint DEFAULT 2 NOT NULL,
	"monthly_rate" double precision DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'available' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "students" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "students_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"student_no" text NOT NULL,
	"full_name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"course" text DEFAULT '' NOT NULL,
	"intake" text DEFAULT '' NOT NULL,
	"emergency_contact" text DEFAULT '' NOT NULL,
	"room_id" bigint,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "students_student_no_unique" UNIQUE("student_no")
);
--> statement-breakpoint
CREATE TABLE "maintenance_tickets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maintenance_tickets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ticket_no" text NOT NULL,
	"student_id" bigint,
	"hostel_id" bigint,
	"unit_id" bigint,
	"room_id" bigint,
	"category" text NOT NULL,
	"subcategory" text DEFAULT '' NOT NULL,
	"subject" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"priority" text DEFAULT 'average' NOT NULL,
	"status" text DEFAULT 'submitted' NOT NULL,
	"submitted_by_type" text DEFAULT 'staff' NOT NULL,
	"assigned_to" text DEFAULT '' NOT NULL,
	"attended_at" text,
	"completed_at" text,
	"cost_responsibility" text DEFAULT 'management' NOT NULL,
	"estimated_cost" double precision,
	"actual_cost" double precision,
	"student_charge" double precision,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	"updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "maintenance_tickets_ticket_no_unique" UNIQUE("ticket_no")
);
--> statement-breakpoint
CREATE TABLE "meter_readings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "meter_readings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"bed_space_id" bigint NOT NULL,
	"room_id" bigint,
	"reading_date" text NOT NULL,
	"reading_value" double precision NOT NULL,
	"reading_type" text DEFAULT 'monthly' NOT NULL,
	"submitted_by" text DEFAULT 'Maintenance Team' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "owner_parking_payments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "owner_parking_payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"unit_id" bigint NOT NULL,
	"parking_lot_id" bigint,
	"period" text DEFAULT '' NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"payment_date" text NOT NULL,
	"method" text DEFAULT 'bank-transfer' NOT NULL,
	"reference" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'paid' NOT NULL,
	"remarks" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "parking_lots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "parking_lots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hostel_id" bigint NOT NULL,
	"unit_id" bigint,
	"lot_number" text NOT NULL,
	"status" text DEFAULT 'available' NOT NULL,
	"notes" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "parking_rentals" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "parking_rentals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"parking_lot_id" bigint NOT NULL,
	"student_id" bigint,
	"tenant_type" text DEFAULT 'in-house' NOT NULL,
	"tenant_name" text NOT NULL,
	"contact_number" text DEFAULT '' NOT NULL,
	"unit_number" text DEFAULT '' NOT NULL,
	"car_plate_number" text DEFAULT '' NOT NULL,
	"car_model" text DEFAULT '' NOT NULL,
	"monthly_rental" double precision DEFAULT 0 NOT NULL,
	"deposit_amount" double precision DEFAULT 0 NOT NULL,
	"start_date" text NOT NULL,
	"end_date" text,
	"paid_until" text,
	"billing_frequency" text DEFAULT 'monthly' NOT NULL,
	"package_months" bigint DEFAULT 1 NOT NULL,
	"next_due_date" text,
	"payment_status" text DEFAULT 'not-due' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"notes" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reminder_templates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reminder_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reminder_key" text NOT NULL,
	"day_of_month" bigint NOT NULL,
	"subject" text NOT NULL,
	"message" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "reminder_templates_reminder_key_unique" UNIQUE("reminder_key")
);
--> statement-breakpoint
CREATE TABLE "reservation_charges" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reservation_charges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reservation_id" bigint NOT NULL,
	"charge_type" text NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"notes" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reservation_payments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reservation_payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reservation_id" bigint NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"reference" text DEFAULT '' NOT NULL,
	"payment_method" text DEFAULT 'bank-transfer' NOT NULL,
	"paid_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	"notes" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reservations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reservations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reference_no" text NOT NULL,
	"student_name" text NOT NULL,
	"reservation_type" text DEFAULT 'individual' NOT NULL,
	"representative_type" text DEFAULT 'person' NOT NULL,
	"sales_person" text DEFAULT '' NOT NULL,
	"group_size" bigint DEFAULT 1 NOT NULL,
	"preferred_hostel_id" bigint,
	"preferred_unit_id" bigint,
	"preferred_gender" text DEFAULT 'unspecified' NOT NULL,
	"room_category" text DEFAULT 'any' NOT NULL,
	"room_type" text DEFAULT 'any' NOT NULL,
	"bathroom_type" text DEFAULT 'any' NOT NULL,
	"target_move_in_date" text NOT NULL,
	"expected_end_date" text,
	"budget_max" double precision,
	"provisional_bed_space_id" bigint,
	"assigned_bed_space_id" bigint,
	"hold_expires_at" text,
	"payment_status" text DEFAULT 'unpaid' NOT NULL,
	"amount_paid" double precision DEFAULT 0 NOT NULL,
	"total_payable" double precision,
	"payment_reference" text DEFAULT '' NOT NULL,
	"inventory_committed" boolean DEFAULT false NOT NULL,
	"payment_updated_at" text,
	"status" text DEFAULT 'reserved' NOT NULL,
	"converted_at" text,
	"notes" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "reservations_reference_no_unique" UNIQUE("reference_no")
);
--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role_id" bigint NOT NULL,
	"module_key" text NOT NULL,
	"can_view" boolean DEFAULT false NOT NULL,
	"can_create" boolean DEFAULT false NOT NULL,
	"can_edit" boolean DEFAULT false NOT NULL,
	"can_delete" boolean DEFAULT false NOT NULL,
	"can_approve" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "schools" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schools_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "schools_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "stored_attachments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stored_attachments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"context_type" text NOT NULL,
	"record_id" bigint NOT NULL,
	"object_key" text NOT NULL,
	"file_name" text NOT NULL,
	"content_type" text DEFAULT 'application/octet-stream' NOT NULL,
	"size_bytes" bigint DEFAULT 0 NOT NULL,
	"uploaded_by" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "stored_attachments_object_key_unique" UNIQUE("object_key")
);
--> statement-breakpoint
CREATE TABLE "student_profiles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"source_key" text NOT NULL,
	"student_code" text DEFAULT '' NOT NULL,
	"full_name" text NOT NULL,
	"identity_no" text DEFAULT '' NOT NULL,
	"contact_number" text DEFAULT '' NOT NULL,
	"email" text DEFAULT '' NOT NULL,
	"date_of_birth" text,
	"gender" text DEFAULT 'unspecified' NOT NULL,
	"race" text DEFAULT '' NOT NULL,
	"religion" text DEFAULT '' NOT NULL,
	"nationality" text DEFAULT '' NOT NULL,
	"hometown" text DEFAULT '' NOT NULL,
	"course" text DEFAULT '' NOT NULL,
	"school" text DEFAULT '' NOT NULL,
	"application_form_no" text DEFAULT '' NOT NULL,
	"receipt_no" text DEFAULT '' NOT NULL,
	"salesperson" text DEFAULT '' NOT NULL,
	"agency" text DEFAULT '' NOT NULL,
	"remarks" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "student_profiles_source_key_unique" UNIQUE("source_key")
);
--> statement-breakpoint
CREATE TABLE "student_rate_changes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_rate_changes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"assignment_id" bigint NOT NULL,
	"effective_date" text NOT NULL,
	"monthly_rental" double precision,
	"security_deposit" double precision,
	"reason" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ticket_categories" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ticket_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"category" text NOT NULL,
	"subcategory" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"sort_order" bigint DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ticket_messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ticket_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ticket_id" bigint NOT NULL,
	"author_name" text NOT NULL,
	"author_role" text DEFAULT 'staff' NOT NULL,
	"message" text NOT NULL,
	"status_after" text,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "unit_owner_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "unit_owner_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"unit_id" bigint NOT NULL,
	"owner_name" text DEFAULT '' NOT NULL,
	"owner_identity_no" text DEFAULT '' NOT NULL,
	"owner_email" text DEFAULT '' NOT NULL,
	"registered_address" text DEFAULT '' NOT NULL,
	"agreement_type" text DEFAULT 'rental' NOT NULL,
	"primary_contact_name" text DEFAULT '' NOT NULL,
	"primary_contact_phone" text DEFAULT '' NOT NULL,
	"secondary_contact_name" text DEFAULT '' NOT NULL,
	"secondary_contact_phone" text DEFAULT '' NOT NULL,
	"bank_account_number" text DEFAULT '' NOT NULL,
	"bank_account_holder" text DEFAULT '' NOT NULL,
	"bank_name" text DEFAULT '' NOT NULL,
	"lease_start_date" text,
	"lease_end_date" text,
	"monthly_lease_rental" double precision,
	"service_percentage" double precision,
	"security_deposit" double precision,
	"utility_deposit" double precision,
	"commission_amount" double precision,
	"tnb_account" text DEFAULT '' NOT NULL,
	"air_selangor_account" text DEFAULT '' NOT NULL,
	"indah_water_account" text DEFAULT '' NOT NULL,
	"monthly_cleaning_fee" double precision,
	"monthly_water_dispenser_fee" double precision,
	"notes" text DEFAULT '' NOT NULL,
	"updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "unit_services" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "unit_services_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"unit_id" bigint NOT NULL,
	"service_type" text NOT NULL,
	"account_holder_name" text DEFAULT '' NOT NULL,
	"provider" text DEFAULT '' NOT NULL,
	"account_reference" text DEFAULT '' NOT NULL,
	"line_type" text DEFAULT 'not-applicable' NOT NULL,
	"contract_end_date" text,
	"service_package" text DEFAULT '' NOT NULL,
	"username" text DEFAULT '' NOT NULL,
	"password" text DEFAULT '' NOT NULL,
	"remarks" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"surrender_action" text DEFAULT 'review' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"user_id" bigint NOT NULL,
	"expires_at" text NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "user_sessions_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
ALTER TABLE "access_cards" ADD CONSTRAINT "access_cards_unit_id_hostel_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accommodation_assignments" ADD CONSTRAINT "accommodation_assignments_student_id_student_profiles_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accommodation_assignments" ADD CONSTRAINT "accommodation_assignments_bed_space_id_bed_spaces_id_fk" FOREIGN KEY ("bed_space_id") REFERENCES "public"."bed_spaces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_hostel_id_hostel_properties_id_fk" FOREIGN KEY ("hostel_id") REFERENCES "public"."hostel_properties"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_unit_id_hostel_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_users" ADD CONSTRAINT "app_users_role_id_app_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."app_roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_users" ADD CONSTRAINT "app_users_student_id_student_profiles_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bed_spaces" ADD CONSTRAINT "bed_spaces_room_id_hostel_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."hostel_rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "billing_invoices" ADD CONSTRAINT "billing_invoices_cycle_id_billing_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."billing_cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "billing_invoices" ADD CONSTRAINT "billing_invoices_student_id_student_profiles_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "billing_invoices" ADD CONSTRAINT "billing_invoices_assignment_id_accommodation_assignments_id_fk" FOREIGN KEY ("assignment_id") REFERENCES "public"."accommodation_assignments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "billing_item_adjustments" ADD CONSTRAINT "billing_item_adjustments_billing_item_id_billing_items_id_fk" FOREIGN KEY ("billing_item_id") REFERENCES "public"."billing_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "billing_items" ADD CONSTRAINT "billing_items_invoice_id_billing_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."billing_invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "billing_payment_records" ADD CONSTRAINT "billing_payment_records_invoice_id_billing_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."billing_invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "billing_payment_records" ADD CONSTRAINT "billing_payment_records_proof_attachment_id_stored_attachments_id_fk" FOREIGN KEY ("proof_attachment_id") REFERENCES "public"."stored_attachments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "general_costs" ADD CONSTRAINT "general_costs_hostel_id_hostel_properties_id_fk" FOREIGN KEY ("hostel_id") REFERENCES "public"."hostel_properties"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "general_costs" ADD CONSTRAINT "general_costs_unit_id_hostel_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "general_costs" ADD CONSTRAINT "general_costs_ticket_id_maintenance_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."maintenance_tickets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hostel_rooms" ADD CONSTRAINT "hostel_rooms_unit_id_hostel_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hostel_units" ADD CONSTRAINT "hostel_units_hostel_id_hostel_properties_id_fk" FOREIGN KEY ("hostel_id") REFERENCES "public"."hostel_properties"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complaints" ADD CONSTRAINT "complaints_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "rooms_hostel_id_hostels_id_fk" FOREIGN KEY ("hostel_id") REFERENCES "public"."hostels"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "students" ADD CONSTRAINT "students_room_id_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "maintenance_tickets_student_id_student_profiles_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "maintenance_tickets_hostel_id_hostel_properties_id_fk" FOREIGN KEY ("hostel_id") REFERENCES "public"."hostel_properties"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "maintenance_tickets_unit_id_hostel_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "maintenance_tickets_room_id_hostel_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."hostel_rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meter_readings" ADD CONSTRAINT "meter_readings_bed_space_id_bed_spaces_id_fk" FOREIGN KEY ("bed_space_id") REFERENCES "public"."bed_spaces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meter_readings" ADD CONSTRAINT "meter_readings_room_id_hostel_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."hostel_rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "owner_parking_payments" ADD CONSTRAINT "owner_parking_payments_unit_id_hostel_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "owner_parking_payments" ADD CONSTRAINT "owner_parking_payments_parking_lot_id_parking_lots_id_fk" FOREIGN KEY ("parking_lot_id") REFERENCES "public"."parking_lots"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parking_lots" ADD CONSTRAINT "parking_lots_hostel_id_hostel_properties_id_fk" FOREIGN KEY ("hostel_id") REFERENCES "public"."hostel_properties"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parking_lots" ADD CONSTRAINT "parking_lots_unit_id_hostel_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parking_rentals" ADD CONSTRAINT "parking_rentals_parking_lot_id_parking_lots_id_fk" FOREIGN KEY ("parking_lot_id") REFERENCES "public"."parking_lots"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parking_rentals" ADD CONSTRAINT "parking_rentals_student_id_student_profiles_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reservation_charges" ADD CONSTRAINT "reservation_charges_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reservation_payments" ADD CONSTRAINT "reservation_payments_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_preferred_hostel_id_hostel_properties_id_fk" FOREIGN KEY ("preferred_hostel_id") REFERENCES "public"."hostel_properties"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_preferred_unit_id_hostel_units_id_fk" FOREIGN KEY ("preferred_unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_provisional_bed_space_id_bed_spaces_id_fk" FOREIGN KEY ("provisional_bed_space_id") REFERENCES "public"."bed_spaces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_assigned_bed_space_id_bed_spaces_id_fk" FOREIGN KEY ("assigned_bed_space_id") REFERENCES "public"."bed_spaces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_app_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."app_roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_rate_changes" ADD CONSTRAINT "student_rate_changes_assignment_id_accommodation_assignments_id_fk" FOREIGN KEY ("assignment_id") REFERENCES "public"."accommodation_assignments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_messages" ADD CONSTRAINT "ticket_messages_ticket_id_maintenance_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."maintenance_tickets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "unit_owner_details" ADD CONSTRAINT "unit_owner_details_unit_id_hostel_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "unit_services" ADD CONSTRAINT "unit_services_unit_id_hostel_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."hostel_units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_app_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "room_bed_unique" ON "bed_spaces" USING btree ("room_id","bed_label");--> statement-breakpoint
CREATE UNIQUE INDEX "hostel_room_unique" ON "hostel_rooms" USING btree ("unit_id","room_label");--> statement-breakpoint
CREATE UNIQUE INDEX "hostel_unit_unique" ON "hostel_units" USING btree ("hostel_id","unit_code");--> statement-breakpoint
CREATE UNIQUE INDEX "parking_lot_unique" ON "parking_lots" USING btree ("hostel_id","lot_number");--> statement-breakpoint
CREATE UNIQUE INDEX "role_permission_unique" ON "role_permissions" USING btree ("role_id","module_key");--> statement-breakpoint
CREATE UNIQUE INDEX "ticket_category_unique" ON "ticket_categories" USING btree ("category","subcategory");--> statement-breakpoint
CREATE UNIQUE INDEX "unit_owner_unique" ON "unit_owner_details" USING btree ("unit_id");