CREATE TABLE "hostel_category_rates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hostel_category_rates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hostel_id" bigint NOT NULL,
	"room_category" text NOT NULL,
	"monthly_rate" double precision NOT NULL,
	"updated_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "hostel_category_rates" ADD CONSTRAINT "hostel_category_rates_hostel_id_hostel_properties_id_fk" FOREIGN KEY ("hostel_id") REFERENCES "public"."hostel_properties"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "hostel_category_rate_unique" ON "hostel_category_rates" USING btree ("hostel_id","room_category");