CREATE TABLE "deposit_adjustments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deposit_adjustments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"assignment_id" bigint NOT NULL,
	"previous_amount" double precision DEFAULT 0 NOT NULL,
	"new_amount" double precision DEFAULT 0 NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"source" text DEFAULT 'rate-change' NOT NULL,
	"effective_date" text NOT NULL,
	"billed_cycle_id" bigint,
	"created_by" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "deposit_adjustments" ADD CONSTRAINT "deposit_adjustments_assignment_id_accommodation_assignments_id_fk" FOREIGN KEY ("assignment_id") REFERENCES "public"."accommodation_assignments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deposit_adjustments" ADD CONSTRAINT "deposit_adjustments_billed_cycle_id_billing_cycles_id_fk" FOREIGN KEY ("billed_cycle_id") REFERENCES "public"."billing_cycles"("id") ON DELETE no action ON UPDATE no action;