CREATE TABLE "races" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "races_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "races_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "religions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "religions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
	CONSTRAINT "religions_name_unique" UNIQUE("name")
);
