CREATE TABLE "reservation_group_tenants" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reservation_group_tenants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reservation_id" bigint NOT NULL,
	"slot_index" bigint NOT NULL,
	"full_name" text DEFAULT '' NOT NULL,
	"identity_no" text DEFAULT '' NOT NULL,
	"contact_number" text DEFAULT '' NOT NULL,
	"gender" text DEFAULT 'unspecified' NOT NULL,
	"is_student" boolean DEFAULT true NOT NULL,
	"is_payer" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "reservations" ADD COLUMN "organisation_name" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "reservations" ADD COLUMN "company_registration_no" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "reservations" ADD COLUMN "organisation_address" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "reservations" ADD COLUMN "company_email" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "reservations" ADD COLUMN "utility_billed_to" text DEFAULT 'tenant' NOT NULL;--> statement-breakpoint
ALTER TABLE "student_profiles" ADD COLUMN "is_student" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "reservation_group_tenants" ADD CONSTRAINT "reservation_group_tenants_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id") ON DELETE no action ON UPDATE no action;