// 套用 0023：新增 races、religions 两张表，并用现有写死的清单
// （Chinese/Malay/Indian/Others、Hinduism/Buddhism/Islam/Christianity/Others）
// 当初始资料填进去。纯新增，不改动任何既有学生/预订资料。
import postgres from "postgres";
const sql = postgres(process.env.DATABASE_URL, {
  prepare: false,
  max: 2,
  idle_timeout: 10,
});
await sql`SET search_path TO public`;

await sql`
  CREATE TABLE IF NOT EXISTS races (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    created_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
  )`;
console.log("races table ready");

await sql`
  CREATE TABLE IF NOT EXISTS religions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    created_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
  )`;
console.log("religions table ready");

const RACES = ["Chinese", "Malay", "Indian", "Others"];
const RELIGIONS = ["Hinduism", "Buddhism", "Islam", "Christianity", "Others"];

for (const name of RACES) {
  await sql`INSERT INTO races (name) VALUES (${name}) ON CONFLICT (name) DO NOTHING`;
}
for (const name of RELIGIONS) {
  await sql`INSERT INTO religions (name) VALUES (${name}) ON CONFLICT (name) DO NOTHING`;
}

const raceRows = await sql`SELECT id, name FROM races ORDER BY id`;
const religionRows = await sql`SELECT id, name FROM religions ORDER BY id`;
console.log("races:", JSON.stringify(raceRows));
console.log("religions:", JSON.stringify(religionRows));

await sql.end();
